[general]
email = "karthikeyancbm1982@gmail.com"

[server]
enableCORS = false
enableXsrfProtection = false

[theme]

primaryColor="#247579"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"
